version: "3.9"

services:
  site-frontend:
    depends_on:
    - database
    container_name: "nginx"
    build: ./site
    ports:
    - "80:80"
  database:
    container_name: "mongodb"
    image: mongo
    volumes:
    - mongovol:/var/lib/mongodb
    - ./database/mongod.conf.orig:/etc/mongod.conf
    enviroment:
    - MONGO_INITDB_ROOT_USERNAME= $MONGO_ROOT_USR
    - MONGO_INITDB_ROOT_PASSWORD= $MONGO_ROOT_PWD
    ports:
    - "27017:27017"

volumes:
  mongovol:
