FROM nginx

RUN apt-get update && apt-get install curl 
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs

COPY default /etc/nginx/sites-available/default

WORKDIR /usr/share/nginx/html
RUN rm -rf *
COPY . ./

EXPOSE 80/tcp

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
