# action for scanning container image and app code for CVE

name: CVE scan

on: workflow_dispatch

jobs:
  DockerImageScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Build docker image
        run: cd site && docker build . --tag scan
             
      - name: Docker image CVE scan
        uses: anchore/scan-action@v3
        with:
          image: "scan"
       
  AppCodeScan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Scan app data
      uses: anchore/scan-action@v3
      with:
        path: "site"
          


          
          
   
