# action for scanning container image and app code for CVE

name: CVE scan

on: workflow_dispatch

jobs:
  DockerImageScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Build docker image
        run: cd site && docker build . --tag scan
             
      - name: Get docker scan plugin  
        run: | 
             mkdir -p ~/.docker/cli-plugins && 
             curl https://github.com/docker/scan-cli-plugin/releases/latest/download/docker-scan_linux_amd64 -L -s -S -o ~/.docker/cli-plugins/docker-scan
             chmod +x ~/.docker/cli-plugins/docker-scan
          
      - name: Docker login and Docker scan
        run: | 
            docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }} 
            docker scan --accept-license scan
        


          
          
   
