name: deploy

on: workflow_dispatch

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get ssh key
    
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        known_hosts: placeholder

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST}} >> ~/.ssh/known_hosts

    - name: Deploy
      run: rsync . ${{ secrets.SSH_USERNAME}}@${{ secrets.SSH_IP}}:/home/vjeks
