name: deploy

on: workflow_dispatch

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get ssh key for remote connection
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        known_hosts: placeholder

    - name: Adding Known Hosts from the server
      run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_IP}} >> ~/.ssh/known_hosts

    - name: Deploy the files via rsync
      run: rsync -vr . ${{ secrets.SSH_USERNAME}}@${{ secrets.SSH_IP}}:/home/vjeks/Aws_Test_Website
      
    - name: show env
      run: env
      
    - name: Starting up docker compose remotely
      uses: appleboy/ssh-action@master
      env:
        MONGO_ROOT_USR: ${{ secrets.MONGO_ROOT_USR }}
        MONGO_ROOT_PWD: ${{ secrets.MONGO_ROOT_PWD }}     
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        port: ${{ secrets.SSH_PORT }}
        script: cd Aws_Test_Website && docker compose build --build-arg MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USR --build-arg MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PWD && docker compose up -d
        

