# Test action to build, tag and upload docker image but without a unified action that does everything at once
# Made in multiple steps with commands

Name: Docker Image build/tag/upload test

on: workflow_dispatch

# This job builds and tags an image, saves it and uploads it as an artifact. The last step sends a slack notification on success
jobs:
  BuildAndTag:
    runs-on: ubunutu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build and tag Docker image
      run: |
           cd site
           docker build . -t test
           docker save test > test.tar
          
    - name: Upload image as artifact      
      uses: actions/upload-artifact@v3
      with:
        name: ImageArtifact
        path: site/test.tar

    - name: Report Success
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notify_when: 'success'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

# This job downloads the image artifact, loads it and pushes it to Dockerhub. The last step sends a slack notification on success
  UploadImage:
    needs: BuildAndTag
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Artifact download
      uses: actions/download-artifact@v3
      with:
        name: ImageArtifact
        
    - name: Load docker image and upload to Dockerhub
      run: |
            docker load --input test.tar
            docker push vdraksic/practice_1:test
            
    - name: Report Success
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notify_when: 'success'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

# This job has the previous two jobs as dependencies and notifies slack on faliure
  SlackReportOnFail:
    needs: [BuildAndTag, UploadImage]
    runs-on: ubuntu-latest
    
    steps:
    - name: Report Success
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notify_when: 'faliure'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  
            
            
      
