# pushes image to Aws repo

name: AWS build and push

on: workflow_dispatch

# setting env vars for programmatic access for the docker-image-push user

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-and-push:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build and tag docker image
      run: |
            cd site && docker build . -t ${{ secrets.AWS_ACC_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_REPO }}:test

    - name: Authenticating Docker client to the ECR registry       
      run: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACC_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Push docker image to ECR
      run: |
            docker push ${{ secrets.AWS_ACC_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_REPO }}:test
                    
            