# Testing action run on PR merge to main

name: TriggerOnMergeToMain

on:
  pull_request:
    branches:
    - 'main'
    types: [closed]
    
jobs:
  build:
   if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
   runs-on: ubuntu-lastest
   steps:
   - name: Testrun
     run: echo test complete!
