# uses git tag to tag and relese docker image on dockerhub

name: Build and release Docker images with git tag

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build Docker image
        uses: flownative/action-docker-build@v1
        with:
          tag_ref: ${{ github.ref }}
          image_name: vdraksic/practice_1
          registry_password: ${{ secrets.GITHUB_TOKEN }}
