# uses git tag to tag and relese docker image on dockerhub
name: Tag and build

on:
  push:
    tags:
      - 'v*'

jobs:
  TagPush:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            vdraksic/practice_1
          tags: |      
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: site
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/practice_1:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/practice_1:buildcache,mode=max
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Report Success
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'success,faliure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
