name: Simple-tag

on:
  push:
    tags:
      - 'v*'

jobs:
  TagPush:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish to Registry
        uses: sergeysova/docker-publish-action@master
        with:
          image: vdraksic/practice_1
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}   
          context: site
          tag_semver: skip